-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 01:59:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema building_cost_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema building_cost_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `building_cost_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `building_cost_db` ;

-- -----------------------------------------------------
-- Table `building_cost_db`.`houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`houses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `floors` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`stages` (
  `id_stages` INT NOT NULL AUTO_INCREMENT,
  `stage_name` VARCHAR(45) NOT NULL,
  `id_stages_of_house` INT NOT NULL,
  PRIMARY KEY (`id_stages`),
  CONSTRAINT `fk_stages_houses`
    FOREIGN KEY (`id_stages_of_house`)
    REFERENCES `building_cost_db`.`houses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 106
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_stages_houses_idx` ON `building_cost_db`.`stages` (`id_stages_of_house` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_stages_houses` ON `building_cost_db`.`stages` (`id_stages_of_house` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`sub_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`sub_stage` (
  `id_sub_stage` INT NOT NULL AUTO_INCREMENT,
  `sub_stage_name` VARCHAR(80) NOT NULL,
  `stages_id_stages` INT NOT NULL,
  PRIMARY KEY (`id_sub_stage`),
  CONSTRAINT `fk_sub_stage_stages1`
    FOREIGN KEY (`stages_id_stages`)
    REFERENCES `building_cost_db`.`stages` (`id_stages`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_sub_stage_stages1_idx` ON `building_cost_db`.`sub_stage` (`stages_id_stages` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`matherial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`matherial` (
  `id_matherial` INT NOT NULL AUTO_INCREMENT,
  `stages_id_matherial` INT NULL DEFAULT NULL,
  `sub_stage_id_sub_stage` INT NULL DEFAULT NULL,
  `matherial_name` VARCHAR(25) NOT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `sum` DOUBLE NOT NULL,
  PRIMARY KEY (`id_matherial`),
  CONSTRAINT `fk_matherial_stages1`
    FOREIGN KEY (`stages_id_matherial`)
    REFERENCES `building_cost_db`.`stages` (`id_stages`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matherial_sub_stage1`
    FOREIGN KEY (`sub_stage_id_sub_stage`)
    REFERENCES `building_cost_db`.`sub_stage` (`id_sub_stage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1577
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_stages1_idx` ON `building_cost_db`.`matherial` (`stages_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_stages1` ON `building_cost_db`.`matherial` (`stages_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_sub_stage1_idx` ON `building_cost_db`.`matherial` (`sub_stage_id_sub_stage` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`matherial_purchased`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`matherial_purchased` (
  `id_matherial` INT NOT NULL AUTO_INCREMENT,
  `matherial_id_matherial` INT NOT NULL,
  `stages_id_matherial` INT NULL DEFAULT NULL,
  `sub_stage_id_sub_stage` INT NULL DEFAULT NULL,
  `matherial_name` VARCHAR(25) NOT NULL,
  `unit` VARCHAR(20) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `sum` DOUBLE NOT NULL,
  PRIMARY KEY (`id_matherial`),
  CONSTRAINT `fk_ matherial_purchased_stages1`
    FOREIGN KEY (`stages_id_matherial`)
    REFERENCES `building_cost_db`.`stages` (`id_stages`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matherial_purchased_matherial1`
    FOREIGN KEY (`matherial_id_matherial`)
    REFERENCES `building_cost_db`.`matherial` (`id_matherial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_matherial_purchased_sub_stage1`
    FOREIGN KEY (`sub_stage_id_sub_stage`)
    REFERENCES `building_cost_db`.`sub_stage` (`id_sub_stage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_ matherial_purchased_stages1_idx` ON `building_cost_db`.`matherial_purchased` (`stages_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_purchased_matherial1_idx` ON `building_cost_db`.`matherial_purchased` (`matherial_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_ matherial_purchased_stages1` ON `building_cost_db`.`matherial_purchased` (`stages_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_purchased_matherial1` ON `building_cost_db`.`matherial_purchased` (`matherial_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_matherial_purchased_sub_stage1_idx` ON `building_cost_db`.`matherial_purchased` (`sub_stage_id_sub_stage` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`payment` (
  `id_payment` INT NOT NULL AUTO_INCREMENT,
  `stages_id_stages` INT NULL DEFAULT NULL,
  `sub_stage_id_sub_stage` INT NULL DEFAULT NULL,
  `matherial_purchased_id_matherial` INT NULL DEFAULT NULL,
  `matherial_name` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL DEFAULT '0',
  `sum` DOUBLE NOT NULL,
  PRIMARY KEY (`id_payment`),
  CONSTRAINT `fk_payment_matherial_purchased1`
    FOREIGN KEY (`matherial_purchased_id_matherial`)
    REFERENCES `building_cost_db`.`matherial_purchased` (`id_matherial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_stages1`
    FOREIGN KEY (`stages_id_stages`)
    REFERENCES `building_cost_db`.`stages` (`id_stages`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_sub_stage1`
    FOREIGN KEY (`sub_stage_id_sub_stage`)
    REFERENCES `building_cost_db`.`sub_stage` (`id_sub_stage`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_payment_matherial_purchased1_idx` ON `building_cost_db`.`payment` (`matherial_purchased_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_payment_stages1_idx` ON `building_cost_db`.`payment` (`stages_id_stages` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_payment_matherial_purchased1` ON `building_cost_db`.`payment` (`matherial_purchased_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_payment_stages1` ON `building_cost_db`.`payment` (`stages_id_stages` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_payment_sub_stage1_idx` ON `building_cost_db`.`payment` (`sub_stage_id_sub_stage` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`history` (
  `id_history` INT NOT NULL AUTO_INCREMENT,
  `matherial_purchased_id_matherial` INT NULL DEFAULT NULL,
  `payment_id_payment` INT NULL DEFAULT NULL,
  `provider` VARCHAR(45) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `price` DOUBLE NOT NULL,
  `sum` DOUBLE NOT NULL,
  `time_buy` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_history`),
  CONSTRAINT `fk_history_matherial_purchased1`
    FOREIGN KEY (`matherial_purchased_id_matherial`)
    REFERENCES `building_cost_db`.`matherial_purchased` (`id_matherial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_history_payment1`
    FOREIGN KEY (`payment_id_payment`)
    REFERENCES `building_cost_db`.`payment` (`id_payment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 86
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `fk_history_matherial_purchased1_idx` ON `building_cost_db`.`history` (`matherial_purchased_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_history_payment1_idx` ON `building_cost_db`.`history` (`payment_id_payment` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_history_matherial_purchased1` ON `building_cost_db`.`history` (`matherial_purchased_id_matherial` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_history_payment1` ON `building_cost_db`.`history` (`payment_id_payment` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `building_cost_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `building_cost_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
